### ISSUE TITLE
Qué le falta?

### ISSUE THREAD

**Issue by fixmycode** [cornershop/python-tbk#1]
Estimado @pedroburon, en mi empresa estamos muy interesados en apoyar el desarrollo de una solución para WebPay Plus en Python, nos gustaría saber si hay algún área en la que podríamos ayudar para adelantar la salida a producción. Hemos ocupado el paquete que habías desarrollado antes, tbk, con éxito, qué diferencia a este desarrollo con el anterior?

**Comment by pedroburon** [comment]
Este desarrollo contempla el api SOAP de tbk, implementa todo el "protocolo" de seguridad requerido por Transbank y el API es mucho más sencilla que la implementada por Transbank en su SDK. 

Faltan varios métodos para los distintos servicios que ofrece TBK, nosotros no estamos utilizando más por el momento pero crear uno nuevo sólo requiere armar el input y llamar al método correcto.

Creo que lo más importante que falta ahora es un roadmap de la librería para que quede _feature complete_, si necesitan algo en particular sería ideal que lo agregaran como issue :)

Saludos y gracias por el interés.
